export interface DevotionalPost {
  id: number;
  period: "morning" | "evening";
  book: string;
  chapter: number;
  verse: number | string;
  scripture: string;
  greeting: string;
  reflection: string;
  blessing: string;
  imageUrl: string;
}

export const DEVOTIONALS: DevotionalPost[] = [
  // ─────────────────────────────────────────────────────────────────
  // ☀️ DEVOCIONAIS DA MANHÃ (BOM DIA)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 1,
    period: "morning",
    book: "Salmos",
    chapter: 143,
    verse: 8,
    scripture: "Faze-me ouvir da tua fidelidade pela manhã, pois em ti confio. Mostra-me o caminho que devo seguir, pois a ti elevo a minha alma.",
    greeting: "Bom dia! Que a presença e a paz de Deus encham o seu coração nesta manhã. ✨",
    reflection: "Antes de mergulhar nas tarefas e correrias do dia, respire fundo e entregue seus planos ao Senhor. Quando começamos o dia ouvindo a voz de Deus, nossos passos ficam mais firmes e as decisões mais sábias.",
    blessing: "Que você tenha um dia produtivo, protegido e cheio da graça de Deus! Vá em paz e com fé. 🙏",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1080&q=80",
  },
  {
    id: 2,
    period: "morning",
    book: "Lamentações",
    chapter: 3,
    verse: "22-23",
    scripture: "As misericórdias do Senhor são inesgotáveis; renovam-se a cada manhã. Grande é a sua fidelidade!",
    greeting: "A paz do Senhor, queridos! Hoje é um novo dia, e com ele vem uma nova oportunidade. ☀️",
    reflection: "Não importa o que deu errado ontem ou as frustrações que você enfrentou. Hoje o Senhor renovou a misericórdia sobre a sua vida. O passado ficou para trás; hoje Deus tem forças novas para você vencer.",
    blessing: "Comece o dia com esperança renovada. Deus já está cuidando de tudo! Um dia abençoado para você. ✨",
    imageUrl: "https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?w=1080&q=80",
  },
  {
    id: 3,
    period: "morning",
    book: "Josué",
    chapter: 1,
    verse: 9,
    scripture: "Não fui eu que ordenei a você? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.",
    greeting: "Bom dia, vencedores! Levante a cabeça com coragem e ânimo. 🦁",
    reflection: "Os desafios de hoje podem parecer grandes, mas o Deus que caminha ao seu lado é infinitamente maior. Não deixe o desânimo paralisar você; avance sabendo que você nunca está desamparado.",
    blessing: "Que a coragem do Espírito Santo guie suas escolhas hoje. Tenha um dia de vitórias e conquistas! 🙏",
    imageUrl: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=1080&q=80",
  },
  {
    id: 4,
    period: "morning",
    book: "Salmos",
    chapter: 37,
    verse: 5,
    scripture: "Entregue o seu caminho ao Senhor; confie nele, e ele agirá.",
    greeting: "Bom dia, família! Que a sua manhã comece leve e cheia de paz. 🕊️",
    reflection: "Nós gastamos tanta energia tentando controlar coisas que fogem do nosso alcance. O segredo da paz é fazer o nosso melhor com dedicação, mas soltar o peso nas mãos dAquele que realmente tem o poder de agir.",
    blessing: "Descanse sua mente e faça sua parte com dedicação. Deus está à frente do seu dia! ✨",
    imageUrl: "https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=1080&q=80",
  },
  {
    id: 5,
    period: "morning",
    book: "Isaías",
    chapter: 41,
    verse: 10,
    scripture: "Por isso não tema, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa.",
    greeting: "Bom dia! Receba esta palavra de força para começar o dia com o coração firme. 🛡️",
    reflection: "Se alguma incerteza tentou roubar sua paz logo cedo, lembre-se: Deus prometeu segurar a sua mão. Você não precisa enfrentar as lutas de hoje sozinho; a força do Alto te sustenta a cada passo.",
    blessing: "Caminhe com a certeza da proteção divina sobre a sua vida e seu trabalho. Um dia abençoado! 🙏",
    imageUrl: "https://images.unsplash.com/photo-1504052434569-70ad5836ab65?w=1080&q=80",
  },
  {
    id: 6,
    period: "morning",
    book: "Provérbios",
    chapter: 3,
    verse: "5-6",
    scripture: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.",
    greeting: "Bom dia na paz de Cristo! Que a sabedoria divina ilumine a sua mente hoje. 💡",
    reflection: "Em cada conversa, decisão e projeto de hoje, peça a orientação de Deus. Ele vê além do que enxergamos e sabe exatamente qual caminho nos conduz à verdadeira paz e realização.",
    blessing: "Que o Senhor abra portas certas e desvie seus passos de todo tropeço. Tenha um dia muito próspero! ✨",
    imageUrl: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1080&q=80",
  },
  {
    id: 7,
    period: "morning",
    book: "Salmos",
    chapter: 118,
    verse: 24,
    scripture: "Este é o dia que fez o Senhor; regozijemo-nos e alegremo-nos nele!",
    greeting: "Bom dia com alegria no coração! Mais um presente de Deus aberto para nós. 🎁",
    reflection: "Acordar com vida e saúde já é motivo suficiente para sermos gratos. Escolha começar o dia focando nas bênçãos, e você verá que até os momentos difíceis se tornam mais leves quando o coração transborda gratidão.",
    blessing: "Sorria e abrace este novo dia com fé e entusiasmo. Que Deus abençoe ricamente a sua vida! 🙏",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1080&q=80",
  },
  {
    id: 8,
    period: "morning",
    book: "Isaías",
    chapter: 40,
    verse: 31,
    scripture: "Mas aqueles que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam.",
    greeting: "Bom dia, guerreiros! Sentindo cansaço? Deus tem renovo para você hoje. 🦅",
    reflection: "A nossa força humana tem limites, mas a força que vem de Deus é inesgotável. Quando colocamos a nossa confiança no Senhor, Ele nos capacita a ir além das nossas próprias capacidades.",
    blessing: "Receba novas energias físicas e espirituais para vencer todas as metas de hoje. Tenha um dia vitorioso! ✨",
    imageUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1080&q=80",
  },
  {
    id: 9,
    period: "morning",
    book: "Salmos",
    chapter: 121,
    verse: "1-2",
    scripture: "Levanto os meus olhos para os montes e pergunto: de onde me vem o socorro? O meu socorro vem do Senhor, que fez os céus e a terra.",
    greeting: "Bom dia, amigos! Onde está o seu foco nesta manhã? 🏔️",
    reflection: "Não olhe apenas para o tamanho dos problemas; olhe para o Deus que governa o universo inteiro. Quem criou os céus e a terra tem todo o poder para intervir e cuidar das suas necessidades hoje.",
    blessing: "Que a certeza do socorro de Deus guarde seus pensamentos durante todo o dia. Vá em paz! 🙏",
    imageUrl: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1080&q=80",
  },
  {
    id: 10,
    period: "morning",
    book: "Filipenses",
    chapter: 4,
    verse: 13,
    scripture: "Tudo posso naquele que me fortalece.",
    greeting: "Bom dia! Comece esta jornada sabendo que você é capacitado por Deus. 💪",
    reflection: "Você não precisa temer as responsabilidades ou cobranças do dia de hoje. Aquele que começou a boa obra em você é fiel para te sustentar em cada etapa do caminho.",
    blessing: "Que a graça e a força do Senhor estejam visíveis em tudo o que suas mãos fizerem hoje. Amém! ✨",
    imageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1080&q=80",
  },

  // ─────────────────────────────────────────────────────────────────
  // 🌙 DEVOCIONAIS DA NOITE (BOA NOITE)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 101,
    period: "evening",
    book: "Salmos",
    chapter: 4,
    verse: 8,
    scripture: "Em paz me deito e logo adormeço, pois só tu, Senhor, me fazes viver em segurança.",
    greeting: "Boa noite, queridos! Que a paz de Deus envolva a sua casa agora. 🌙",
    reflection: "O dia de hoje chegou ao fim. As batalhas que você travou já passaram e você venceu mais uma jornada. Não leve as preocupações ou a lista de afazeres para a cama; agora é momento de soltar o peso e deixar Deus cuidar do amanhã.",
    blessing: "Deite a cabeça no travesseiro com o coração tranquilo. Tenha uma noite de sono suave e revigorante! Até amanhã. 🤍",
    imageUrl: "https://images.unsplash.com/photo-1510784722466-f2aa9c52fff6?w=1080&q=80",
  },
  {
    id: 102,
    period: "evening",
    book: "Provérbios",
    chapter: 3,
    verse: 24,
    scripture: "Quando você se deitar, não terá medo; o seu sono será tranquilo e suave.",
    greeting: "Boa noite, família! Hora de desacelerar os pensamentos e descansar. 🕯️",
    reflection: "Muitas vezes a mente teima em continuar correndo mesmo quando o corpo pede descanso. Faça uma oração silenciosa, entregue cada ansiedade nas mãos de Jesus e permita que o Espírito Santo acalme a sua alma.",
    blessing: "Que os anjos do Senhor acampem ao redor do seu lar. Durma em perfeita paz e segurança! 🙏",
    imageUrl: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=1080&q=80",
  },
  {
    id: 103,
    period: "evening",
    book: "Mateus",
    chapter: 11,
    verse: 28,
    scripture: "Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso.",
    greeting: "Boa noite! Sentindo o cansaço do dia que passou? Há um convite especial para você. 🕊️",
    reflection: "Jesus conhece o peso das suas responsabilidades e as lutas silenciosas que ninguém mais vê. Ele não quer que você carregue tudo sozinho; o descanso que Ele oferece restaura não apenas o corpo, mas também as emoções e o espírito.",
    blessing: "Descarregue todo o cansaço aos pés da cruz e receba o refrigério do Senhor. Tenha uma noite de sono abençoado! ✨",
    imageUrl: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=1080&q=80",
  },
  {
    id: 104,
    period: "evening",
    book: "Salmos",
    chapter: 121,
    verse: "3-4",
    scripture: "Aquele que o guarda não dormirá. Com efeito, não dormirá nem cochilará o guarda de Israel.",
    greeting: "Boa noite na graça do Senhor! Você pode descansar porque Deus continua velando. 🛡️",
    reflection: "Nós precisamos de sono e pausa, mas o Deus que cuida de nós nunca se cansa e nunca fecha os olhos. Enquanto você dorme e descansa, o Senhor continua trabalhando e protegendo a sua vida e a sua família.",
    blessing: "Deixe as vigílias da noite com o Guarda fiel. Durma sob a sombra das asas do Todo-Poderoso! 🙏",
    imageUrl: "https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?w=1080&q=80",
  },
  {
    id: 105,
    period: "evening",
    book: "Filipenses",
    chapter: 4,
    verse: 7,
    scripture: "E a paz de Deus, que excede todo o entendimento, guardará os seus corações e as suas mentes em Cristo Jesus.",
    greeting: "Boa noite, amados! Que nenhuma ansiedade roube a serenidade da sua noite. 🌿",
    reflection: "A paz do mundo depende de as circunstâncias estarem perfeitas, mas a paz de Deus é maior do que qualquer problema terreno. Ela guarda nossa mente contra pensamentos de angústia e nos dá calma mesmo em meio aos desafios.",
    blessing: "Que a paz que ultrapassa todo entendimento tome conta do seu ser agora. Descanse com Deus! 🤍",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1080&q=80",
  },
  {
    id: 106,
    period: "evening",
    book: "Salmos",
    chapter: 91,
    verse: "1-2",
    scripture: "Aquele que habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso pode dizer ao Senhor: 'Tu és o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.'",
    greeting: "Boa noite! O lugar mais seguro para terminar o dia é debaixo da proteção do Altíssimo. 🏰",
    reflection: "Não importa o que as notícias dizem ou as incertezas ao redor. A sua casa e a sua vida estão guardadas pelo Deus Todo-Poderoso. No esconderijo dEle, não há perigo que possa prevalecer.",
    blessing: "Durma protegido e cercado pelo favor de Deus. Uma noite abençoada para você e toda a sua família! 🙏",
    imageUrl: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=1080&q=80",
  },
  {
    id: 107,
    period: "evening",
    book: "1 Pedro",
    chapter: 5,
    verse: 7,
    scripture: "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.",
    greeting: "Boa noite! Antes de fechar os olhos, solte o que está apertando o seu peito. 🍃",
    reflection: "Deus sabe de cada detalhe que te aflige e Ele se importa verdadeiramente com você. Lançar a ansiedade é um ato de confiança de quem sabe que o Pai cuida até dos passarinhos e das flores do campo.",
    blessing: "Entregue o amanhã nas mãos de quem já está lá. Tenha uma noite de descanso profundo e restaurador! ✨",
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1080&q=80",
  },
  {
    id: 108,
    period: "evening",
    book: "Salmos",
    chapter: 127,
    verse: 2,
    scripture: "Inútil acordar cedo e dormir tarde, trabalhando arduamente por alimento; pois aos seus amados o Senhor concede o sono.",
    greeting: "Boa noite, guerreiros! O trabalho de hoje acabou; agora é hora de receber o presente do sono. 🛏️",
    reflection: "Trabalhar com zelo é bom, mas viver angustiado por medo do futuro não é plano de Deus. Ele ama você e quer te presentear com uma noite de repouso restaurador para que amanhã você acorde com novas forças.",
    blessing: "Acalme o coração e receba o descanso concedido pelo Senhor. Tenha uma noite muito abençoada! 🤍",
    imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1080&q=80",
  },
  {
    id: 109,
    period: "evening",
    book: "1 Tessalonicenses",
    chapter: 5,
    verse: 18,
    scripture: "Dêem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.",
    greeting: "Boa noite na paz de Jesus! Vamos terminar o dia com um coração agradecido? 🌸",
    reflection: "Mesmo que o dia não tenha sido perfeito, houve livramentos que você viu e outros que você nem percebeu. O ar nos pulmões, a vida, o pão e a proteção do Senhor são motivos diários de gratidão.",
    blessing: "Que a gratidão feche as portas para qualquer tristeza e traga uma noite doce e serena para você. Durma em paz! 🙏",
    imageUrl: "https://images.unsplash.com/photo-1504052434569-70ad5836ab65?w=1080&q=80",
  },
  {
    id: 110,
    period: "evening",
    book: "Salmos",
    chapter: 3,
    verse: 5,
    scripture: "Eu me deito e durmo, e torno a acordar, porque é o Senhor que me sustenta.",
    greeting: "Boa noite! Descanse sabendo quem é que sustenta a sua vida a cada instante. 🌌",
    reflection: "Não são as nossas próprias forças ou estratégias que nos mantêm de pé; é a mão invisível e bondosa de Deus. Você pode fechar os olhos em paz porque o mesmo Senhor que te sustentou hoje estará lá para te acordar amanhã.",
    blessing: "Uma noite de descanso reconfortante e paz profunda para o seu coração. Até amanhã, se Deus quiser! ✨",
    imageUrl: "https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?w=1080&q=80",
  },
];
