export type DayPeriod = "morning" | "evening" | "any";

export interface BibleVerse {
  id: number;
  book: string;
  chapter: number;
  verse: number | string;
  text: string;
  version: "NVI" | "ACF";
  theme: "Paz" | "Fé" | "Força" | "Sabedoria" | "Esperança" | "Amor" | "Gratidão" | "Proteção" | "Descanso";
  period: DayPeriod;
}

export const CURATED_VERSES: BibleVerse[] = [
  // ─── ☀️ VERSÍCULOS DA MANHÃ (BOM DIA / ÂNIMO / FORÇA / VITÓRIA) ────
  {
    id: 1,
    book: "Salmos",
    chapter: 143,
    verse: 8,
    text: "Faze-me ouvir da tua fidelidade pela manhã, pois em ti confio. Mostra-me o caminho que devo seguir, pois a ti elevo a minha alma.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 2,
    book: "Lamentações",
    chapter: 3,
    verse: "22-23",
    text: "Graças ao grande amor do Senhor é que não somos consumidos, pois as suas misericórdias são inesgotáveis. Renovam-se a cada manhã; grande é a sua fidelidade!",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 3,
    book: "Salmos",
    chapter: 5,
    verse: 3,
    text: "De manhã, Senhor, ouves a minha voz; de manhã te apresento a minha oração e fico esperando com esperança.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 4,
    book: "Salmos",
    chapter: 118,
    verse: 24,
    text: "Este é o dia que fez o Senhor; regozijemo-nos e alegremo-nos nele!",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 5,
    book: "Josué",
    chapter: 1,
    verse: 9,
    text: "Não fui eu que ordenei a você? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 6,
    book: "Isaías",
    chapter: 41,
    verse: 10,
    text: "Por isso não tema, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 7,
    book: "Provérbios",
    chapter: 3,
    verse: "5-6",
    text: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 8,
    book: "Jeremias",
    chapter: 29,
    verse: 11,
    text: "Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor, planos de fazê-los prosperar e não de causar dano, planos de dar a vocês esperança e um futuro.",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 9,
    book: "Salmos",
    chapter: 30,
    verse: 5,
    text: "O choro pode durar uma noite, mas a alegria vem pela manhã com o nascer do sol.",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 10,
    book: "Salmos",
    chapter: 90,
    verse: 14,
    text: "Sacia-nos de manhã com o teu amor leal, para que cantemos de alegria e nos regozijemos todos os nossos dias.",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 11,
    book: "Filipenses",
    chapter: 4,
    verse: 13,
    text: "Tudo posso naquele que me fortalece.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 12,
    book: "Salmos",
    chapter: 37,
    verse: 5,
    text: "Entregue o seu caminho ao Senhor; confie nele, e ele tudo fará.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 13,
    book: "Isaías",
    chapter: 40,
    verse: 31,
    text: "Mas aqueles que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 14,
    book: "Mateus",
    chapter: 6,
    verse: 33,
    text: "Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 15,
    book: "Salmos",
    chapter: 121,
    verse: "1-2",
    text: "Levanto os meus olhos para os montes e pergunto: de onde me vem o socorro? O meu socorro vem do Senhor, que fez os céus e a terra.",
    version: "NVI",
    theme: "Proteção",
    period: "morning",
  },
  {
    id: 16,
    book: "Provérbios",
    chapter: 16,
    verse: 3,
    text: "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 17,
    book: "Romanos",
    chapter: 8,
    verse: 31,
    text: "Que diremos, pois, diante dessas coisas? Se Deus é por nós, quem será contra nós?",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },

  // ─── 🌙 VERSÍCULOS DA NOITE (BOA NOITE / PAZ / DESCANSO / SONO) ────
  {
    id: 101,
    book: "Salmos",
    chapter: 4,
    verse: 8,
    text: "Em paz me deito e logo adormeço, pois só tu, Senhor, me fazes viver em segurança.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 102,
    book: "Provérbios",
    chapter: 3,
    verse: 24,
    text: "Quando você se deitar, não terá medo; o seu sono será tranquilo e suave.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 103,
    book: "Salmos",
    chapter: 91,
    verse: "1-2",
    text: "Aquele que habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso pode dizer ao Senhor: 'Tu és o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.'",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 104,
    book: "Salmos",
    chapter: 91,
    verse: 5,
    text: "Você não temerá o pavor da noite nem a flecha que voa de dia.",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 105,
    book: "Mateus",
    chapter: 11,
    verse: 28,
    text: "Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 106,
    book: "Salmos",
    chapter: 121,
    verse: "3-4",
    text: "Ele não permitirá que você tropece; aquele que o guarda não dormirá. Com efeito, não dormirá nem cochilará o guarda de Israel.",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 107,
    book: "Filipenses",
    chapter: 4,
    verse: 7,
    text: "E a paz de Deus, que excede todo o entendimento, guardará os seus corações e as suas mentes em Cristo Jesus.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 108,
    book: "1 Pedro",
    chapter: 5,
    verse: 7,
    text: "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 109,
    book: "Salmos",
    chapter: 23,
    verse: "1-3",
    text: "O Senhor é o meu pastor; de nada terei falta. Em verdes pastagens me faz repousar e me conduz a águas tranquilas; restaura-me as forças.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 110,
    book: "João",
    chapter: 14,
    verse: 27,
    text: "Deixo-lhes a paz; a minha paz lhes dou. Não lha dou como o mundo a dá. Não se perturbe o seu coração, nem tenham medo.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 111,
    book: "Salmos",
    chapter: 127,
    verse: 2,
    text: "Inútil acordar cedo e dormir tarde, trabalhando arduamente por alimento; pois aos seus amados o Senhor concede o sono reparador.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 112,
    book: "Salmos",
    chapter: 63,
    verse: "6-7",
    text: "Quando me deito, lembro-me de ti; penso em ti durante as vigílias da noite. Porque tu és o meu auxílio, canto de alegria à sombra das tuas asas.",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 113,
    book: "1 Tessalonicenses",
    chapter: 5,
    verse: 18,
    text: "Dêem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 114,
    book: "Salmos",
    chapter: 46,
    verse: 10,
    text: "Aquietai-vos e sabei que eu sou Deus; sou exaltado entre as nações, sou exaltado na terra.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 115,
    book: "Salmos",
    chapter: 3,
    verse: 5,
    text: "Eu me deito e durmo, e torno a acordar, porque é o Senhor que me sustenta.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
];
