export type DayPeriod = "morning" | "evening" | "any";

export type VerseTheme =
  | "Paz"
  | "Fé"
  | "Força"
  | "Sabedoria"
  | "Esperança"
  | "Amor"
  | "Gratidão"
  | "Proteção"
  | "Descanso";

export interface BibleVerse {
  id: number;
  book: string;
  chapter: number;
  verse: number | string;
  text: string;
  version: "NVI" | "ACF";
  theme: VerseTheme;
  period: DayPeriod;
}

export const CURATED_VERSES: BibleVerse[] = [
  // ─────────────────────────────────────────────────────────────────
  // ☀️ VERSÍCULOS DA MANHÃ (BOM DIA / ÂNIMO / FORÇA / DIREÇÃO / FÉ)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 1,
    book: "Salmos",
    chapter: 143,
    verse: 8,
    text: "Faze-me ouvir da tua fidelidade pela manhã, pois em ti confio. Mostra-me o caminho que devo seguir, pois a ti elevo a minha alma.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 2,
    book: "Lamentações",
    chapter: 3,
    verse: "22-23",
    text: "Graças ao grande amor do Senhor é que não somos consumidos, pois as suas misericórdias são inesgotáveis. Renovam-se a cada manhã; grande é a sua fidelidade!",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 3,
    book: "Salmos",
    chapter: 5,
    verse: 3,
    text: "De manhã, Senhor, ouves a minha voz; de manhã te apresento a minha oração e fico esperando com esperança.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 4,
    book: "Salmos",
    chapter: 118,
    verse: 24,
    text: "Este é o dia que fez o Senhor; regozijemo-nos e alegremo-nos nele!",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 5,
    book: "Josué",
    chapter: 1,
    verse: 9,
    text: "Não fui eu que ordenei a você? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 6,
    book: "Isaías",
    chapter: 41,
    verse: 10,
    text: "Por isso não tema, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 7,
    book: "Provérbios",
    chapter: 3,
    verse: "5-6",
    text: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 8,
    book: "Jeremias",
    chapter: 29,
    verse: 11,
    text: "Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor, planos de fazê-los prosperar e não de causar dano, planos de dar a vocês esperança e um futuro.",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 9,
    book: "Salmos",
    chapter: 30,
    verse: 5,
    text: "O choro pode durar uma noite, mas a alegria vem pela manhã com o nascer do sol.",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 10,
    book: "Salmos",
    chapter: 90,
    verse: 14,
    text: "Sacia-nos de manhã com o teu amor leal, para que cantemos de alegria e nos regozijemos todos os nossos dias.",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 11,
    book: "Filipenses",
    chapter: 4,
    verse: 13,
    text: "Tudo posso naquele que me fortalece.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 12,
    book: "Salmos",
    chapter: 37,
    verse: 5,
    text: "Entregue o seu caminho ao Senhor; confie nele, e ele tudo fará.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 13,
    book: "Isaías",
    chapter: 40,
    verse: 31,
    text: "Mas aqueles que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 14,
    book: "Mateus",
    chapter: 6,
    verse: 33,
    text: "Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 15,
    book: "Salmos",
    chapter: 121,
    verse: "1-2",
    text: "Levanto os meus olhos para os montes e pergunto: de onde me vem o socorro? O meu socorro vem do Senhor, que fez os céus e a terra.",
    version: "NVI",
    theme: "Proteção",
    period: "morning",
  },
  {
    id: 16,
    book: "Provérbios",
    chapter: 16,
    verse: 3,
    text: "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 17,
    book: "Romanos",
    chapter: 8,
    verse: 31,
    text: "Que diremos, pois, diante dessas coisas? Se Deus é por nós, quem será contra nós?",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 18,
    book: "Salmos",
    chapter: 27,
    verse: 1,
    text: "O Senhor é a minha luz e a minha salvação; de quem terei temor? O Senhor é a fortaleza da minha vida; de quem terei medo?",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 19,
    book: "Salmos",
    chapter: 46,
    verse: 1,
    text: "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade.",
    version: "NVI",
    theme: "Proteção",
    period: "morning",
  },
  {
    id: 20,
    book: "Efésios",
    chapter: 6,
    verse: 10,
    text: "Finalmente, fortaleçam-se no Senhor e no seu forte poder.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 21,
    book: "Salmos",
    chapter: 19,
    verse: 14,
    text: "Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, Senhor, Rocha minha e Redentor meu!",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 22,
    book: "Salmos",
    chapter: 119,
    verse: 105,
    text: "A tua palavra é lâmpada que ilumina os meus passos e luz que clareia o meu caminho.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 23,
    book: "2 Coríntios",
    chapter: 12,
    verse: 9,
    text: "Mas ele me disse: 'Minha graça é suficiente para você, pois o meu poder se aperfeiçoa na fraqueza.' Portanto, eu me gloriarei ainda mais alegremente em minhas fraquezas, para que o poder de Cristo repouse em mim.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 24,
    book: "Salmos",
    chapter: 28,
    verse: 7,
    text: "O Senhor é a minha força e o meu escudo; nele o meu coração confia, e dele recebo ajuda. Meu coração exulta de alegria, e com o meu cântico lhe darei graças.",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 25,
    book: "Colossenses",
    chapter: 3,
    verse: 23,
    text: "Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 26,
    book: "Salmos",
    chapter: 16,
    verse: 8,
    text: "Sempre tenho o Senhor diante de mim. Com ele à minha direita, não serei abalado.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 27,
    book: "Salmos",
    chapter: 84,
    verse: 11,
    text: "Porque o Senhor Deus é sol e escudo; o Senhor dá graça e glória; nenhum bem sonega aos que andam retamente.",
    version: "NVI",
    theme: "Proteção",
    period: "morning",
  },
  {
    id: 28,
    book: "Hebreus",
    chapter: 11,
    verse: 1,
    text: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 29,
    book: "Salmos",
    chapter: 25,
    verse: "4-5",
    text: "Mostra-me, Senhor, os teus caminhos, ensina-me as tuas veredas; guia-me com a tua verdade e ensina-me, pois tu és Deus, meu Salvador, e a minha esperança está em ti o dia todo.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 30,
    book: "Gálatas",
    chapter: 6,
    verse: 9,
    text: "E não nos cansemos de fazer o bem, pois no tempo próprio colheremos, se não desanimarmos.",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 31,
    book: "Tiago",
    chapter: 1,
    verse: 5,
    text: "Se algum de vocês tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 32,
    book: "Salmos",
    chapter: 34,
    verse: 8,
    text: "Provem e vejam como o Senhor é bom. Como é feliz o homem que nele se refugia!",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 33,
    book: "1 Crônicas",
    chapter: 16,
    verse: 11,
    text: "Olhem para o Senhor e para a sua força; busquem sempre a sua face.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 34,
    book: "Romanos",
    chapter: 12,
    verse: 12,
    text: "Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 35,
    book: "Salmos",
    chapter: 103,
    verse: "1-2",
    text: "Bendiga o Senhor a minha alma! Bendiga o Senhor todo o meu ser, e não se esqueça de nenhum de seus benefícios!",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 36,
    book: "Isaías",
    chapter: 26,
    verse: 3,
    text: "Tu guardarás em perfeita paz aquele cujo propósito está firme, porque em ti confia.",
    version: "NVI",
    theme: "Paz",
    period: "morning",
  },
  {
    id: 37,
    book: "Salmos",
    chapter: 138,
    verse: 8,
    text: "O Senhor cumprirá o seu propósito para comigo! O teu amor, Senhor, permanece para sempre; não desampares as obras das tuas mãos.",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 38,
    book: "Miqueias",
    chapter: 7,
    verse: 7,
    text: "Mas, quanto a mim, ficarei atento ao Senhor, esperando em Deus, o meu Salvador, pois o meu Deus me ouvirá.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 39,
    book: "Sofonias",
    chapter: 3,
    verse: 17,
    text: "O Senhor, o seu Deus, está em seu meio, poderoso para salvar. Ele se regozijará em você com alegria, com o seu amor a renovará, ele se regozijará em você com cânticos.",
    version: "NVI",
    theme: "Amor",
    period: "morning",
  },
  {
    id: 40,
    book: "Deuteronômio",
    chapter: 31,
    verse: 8,
    text: "O próprio Senhor irá à sua frente e estará com você; ele nunca o deixará, nunca o abandonará. Não tenha medo! Não desanime!",
    version: "NVI",
    theme: "Proteção",
    period: "morning",
  },
  {
    id: 41,
    book: "Salmos",
    chapter: 18,
    verse: 2,
    text: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio; ele é o meu escudo e o poder que me salva, a minha torre alta.",
    version: "NVI",
    theme: "Proteção",
    period: "morning",
  },
  {
    id: 42,
    book: "Salmos",
    chapter: 119,
    verse: 114,
    text: "Tu és o meu abrigo e o meu escudo; e na tua palavra coloquei a minha esperança.",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 43,
    book: "2 Timóteo",
    chapter: 1,
    verse: 7,
    text: "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 44,
    book: "Salmos",
    chapter: 63,
    verse: 1,
    text: "Ó Deus, tu és o meu Deus, eu te busco intensamente; a minha alma tem sede de ti! Todo o meu ser anseia por ti, numa terra seca, exausta e sem água.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 45,
    book: "Salmos",
    chapter: 32,
    verse: 8,
    text: "Eu o instruirei e o ensinarei no caminho que você deve seguir; eu o aconselharei a cuidar de você.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 46,
    book: "Provérbios",
    chapter: 4,
    verse: 23,
    text: "Acima de tudo, guarde o seu coração, pois dele procedem as fontes da vida.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 47,
    book: "1 Pedro",
    chapter: 1,
    verse: 3,
    text: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo! Conforme a sua grande misericórdia, ele nos regenerou para uma esperança viva, por meio da ressurreição de Jesus Cristo dentre os mortos.",
    version: "NVI",
    theme: "Esperança",
    period: "morning",
  },
  {
    id: 48,
    book: "Mateus",
    chapter: 5,
    verse: 16,
    text: "Assim brilhe a luz de vocês diante dos homens, para que vejam as suas boas obras e glorifiquem ao Pai de vocês, que está nos céus.",
    version: "NVI",
    theme: "Sabedoria",
    period: "morning",
  },
  {
    id: 49,
    book: "Romanos",
    chapter: 8,
    verse: 28,
    text: "Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito.",
    version: "NVI",
    theme: "Fé",
    period: "morning",
  },
  {
    id: 50,
    book: "Salmos",
    chapter: 100,
    verse: "1-2",
    text: "Aclamem o Senhor todos os habitantes da terra! Prestem culto ao Senhor com alegria; entrem na sua presença com cânticos alegres.",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 51,
    book: "Isaías",
    chapter: 43,
    verse: 2,
    text: "Quando você atravessar as águas, eu estarei com você; quando você atravessar os rios, eles não o encobrirão. Quando você andar através do fogo, não se queimará; as chamas não o consumirão.",
    version: "NVI",
    theme: "Proteção",
    period: "morning",
  },
  {
    id: 52,
    book: "Habacuque",
    chapter: 3,
    verse: 19,
    text: "O Senhor Deus é a minha fortaleza, ele torna os meus pés como os da corça e me faz andar em lugares altos.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 53,
    book: "Salmos",
    chapter: 73,
    verse: 26,
    text: "O meu corpo e o meu coração poderão fraquejar, mas Deus é a força do meu coração e a minha herança para sempre.",
    version: "NVI",
    theme: "Força",
    period: "morning",
  },
  {
    id: 54,
    book: "1 Tessalonicenses",
    chapter: 5,
    verse: "16-18",
    text: "Alegrem-se sempre, orem continuamente, dêem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.",
    version: "NVI",
    theme: "Gratidão",
    period: "morning",
  },
  {
    id: 55,
    book: "Salmos",
    chapter: 119,
    verse: 165,
    text: "Os que amam a tua lei desfrutam de grande paz, e nada os faz tropeçar.",
    version: "NVI",
    theme: "Paz",
    period: "morning",
  },

  // ─────────────────────────────────────────────────────────────────
  // 🌙 VERSÍCULOS DA NOITE (BOA NOITE / PAZ / DESCANSO / SONO / PROTEÇÃO)
  // ─────────────────────────────────────────────────────────────────
  {
    id: 101,
    book: "Salmos",
    chapter: 4,
    verse: 8,
    text: "Em paz me deito e logo adormeço, pois só tu, Senhor, me fazes viver em segurança.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 102,
    book: "Provérbios",
    chapter: 3,
    verse: 24,
    text: "Quando você se deitar, não terá medo; o seu sono será tranquilo e suave.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 103,
    book: "Salmos",
    chapter: 91,
    verse: "1-2",
    text: "Aquele que habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso pode dizer ao Senhor: 'Tu és o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.'",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 104,
    book: "Salmos",
    chapter: 91,
    verse: 4,
    text: "Ele o cobrirá com as suas penas, e sob as suas asas você encontrará refúgio; a fidelidade dele será o seu escudo protetor.",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 105,
    book: "Salmos",
    chapter: 91,
    verse: 5,
    text: "Você não temerá o pavor da noite nem a flecha que voa de dia.",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 106,
    book: "Mateus",
    chapter: 11,
    verse: 28,
    text: "Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 107,
    book: "Salmos",
    chapter: 121,
    verse: "3-4",
    text: "Ele não permitirá que você tropece; aquele que o guarda não dormirá. Com efeito, não dormirá nem cochilará o guarda de Israel.",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 108,
    book: "Filipenses",
    chapter: 4,
    verse: "6-7",
    text: "Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus. E a paz de Deus, que excede todo o entendimento, guardará os seus corações e as suas mentes em Cristo Jesus.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 109,
    book: "1 Pedro",
    chapter: 5,
    verse: 7,
    text: "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 110,
    book: "Salmos",
    chapter: 23,
    verse: "1-3",
    text: "O Senhor é o meu pastor; de nada terei falta. Em verdes pastagens me faz repousar e me conduz a águas tranquilas; restaura-me as forças.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 111,
    book: "João",
    chapter: 14,
    verse: 27,
    text: "Deixo-lhes a paz; a minha paz lhes dou. Não lha dou como o mundo a dá. Não se perturbe o seu coração, nem tenham medo.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 112,
    book: "Salmos",
    chapter: 127,
    verse: 2,
    text: "Inútil acordar cedo e dormir tarde, trabalhando arduamente por alimento; pois aos seus amados o Senhor concede o sono reparador.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 113,
    book: "Salmos",
    chapter: 63,
    verse: "6-7",
    text: "Quando me deito, lembro-me de ti; penso em ti durante as vigílias da noite. Porque tu és o meu auxílio, canto de alegria à sombra das tuas asas.",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 114,
    book: "1 Tessalonicenses",
    chapter: 5,
    verse: 18,
    text: "Dêem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 115,
    book: "Salmos",
    chapter: 46,
    verse: 10,
    text: "Aquietai-vos e sabei que eu sou Deus; sou exaltado entre as nações, sou exaltado na terra.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 116,
    book: "Salmos",
    chapter: 3,
    verse: 5,
    text: "Eu me deito e durmo, e torno a acordar, porque é o Senhor que me sustenta.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 117,
    book: "Salmos",
    chapter: 16,
    verse: 7,
    text: "Bendirei o Senhor, que me aconselha; na escuridão da noite o meu coração me ensina.",
    version: "NVI",
    theme: "Sabedoria",
    period: "evening",
  },
  {
    id: 118,
    book: "Salmos",
    chapter: 34,
    verse: 7,
    text: "O anjo do Senhor acampa-se ao redor dos que o temem e os livra.",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 119,
    book: "Salmos",
    chapter: 42,
    verse: 8,
    text: "Conceda-me o Senhor o seu amor de dia; de noite esteja comigo a sua canção, a minha oração ao Deus da minha vida.",
    version: "NVI",
    theme: "Amor",
    period: "evening",
  },
  {
    id: 120,
    book: "Salmos",
    chapter: 62,
    verse: "1-2",
    text: "A minha alma descansa somente em Deus; dele vem a minha salvação. Somente ele é a rocha que me salva; ele é a minha torre segura! Jamais serei abalado!",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 121,
    book: "Salmos",
    chapter: 62,
    verse: 5,
    text: "Descanse somente em Deus, ó minha alma; dele vem a minha esperança.",
    version: "NVI",
    theme: "Esperança",
    period: "evening",
  },
  {
    id: 122,
    book: "Salmos",
    chapter: 139,
    verse: "11-12",
    text: "Mesmo que eu disser: 'As trevas me encobrirão, e a luz se tornará noite ao meu redor', até as trevas não serão escuras para ti; a noite brilhará como o dia, pois para ti as trevas são luz.",
    version: "NVI",
    theme: "Fé",
    period: "evening",
  },
  {
    id: 123,
    book: "Salmos",
    chapter: 134,
    verse: "1-2",
    text: "Venham, bendigam ao Senhor todos vocês, servos do Senhor, vocês que servem de noite na casa do Senhor. Levantem as mãos no santuário e bendigam ao Senhor!",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 124,
    book: "Salmos",
    chapter: 116,
    verse: 7,
    text: "Retorne ao seu descanso, ó minha alma, porque o Senhor tem sido bom para você!",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 125,
    book: "Êxodo",
    chapter: 33,
    verse: 14,
    text: "Respondeu o Senhor: 'A minha presença irá com você, e eu lhe darei descanso.'",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 126,
    book: "Mateus",
    chapter: 6,
    verse: 34,
    text: "Portanto, não se preocupem com o amanhã, pois o amanhã trará as suas próprias preocupações. Basta a cada dia o seu próprio mal.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 127,
    book: "Salmos",
    chapter: 119,
    verse: 55,
    text: "De noite me lembro do teu nome, Senhor, e guardo a tua lei.",
    version: "NVI",
    theme: "Fé",
    period: "evening",
  },
  {
    id: 128,
    book: "Salmos",
    chapter: 119,
    verse: 62,
    text: "À meia-noite me levanto para te dar graças pelas tuas justas ordenanças.",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 129,
    book: "Provérbios",
    chapter: 19,
    verse: 23,
    text: "O temor do Senhor conduz à vida; quem o tem descansa satisfeito e não é visitado pelo mal.",
    version: "NVI",
    theme: "Descanso",
    period: "evening",
  },
  {
    id: 130,
    book: "Isaías",
    chapter: 32,
    verse: "17-18",
    text: "O efeito da justiça será paz; e a obra da justiça, repouso e segurança para sempre. O meu povo habitará em moradas de paz, em moradas bem seguras e em lugares calmos de descanso.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 131,
    book: "Salmos",
    chapter: 55,
    verse: 22,
    text: "Entregue suas preocupações ao Senhor, e ele o susterá; jamais permitirá que o justo seja abalado.",
    version: "NVI",
    theme: "Fé",
    period: "evening",
  },
  {
    id: 132,
    book: "2 Tessalonicenses",
    chapter: 3,
    verse: 16,
    text: "Ora, o Senhor da paz, ele mesmo, dê a vocês a paz em todo o tempo e de todas as maneiras. O Senhor seja com todos vocês.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 133,
    book: "Salmos",
    chapter: 107,
    verse: "29-30",
    text: "Ele acalmou a tempestade até virar uma brisa, e as ondas do mar se aquietaram. Eles se alegraram quando as águas se acalmaram, e ele os conduziu ao porto seguro.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 134,
    book: "João",
    chapter: 16,
    verse: 33,
    text: "Eu lhes disse essas coisas para que em mim vocês tenham paz. No mundo vocês terão aflições; contudo, tenham bom ânimo! Eu venci o mundo.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 135,
    book: "Romanos",
    chapter: 15,
    verse: 13,
    text: "Que o Deus da esperança os encha de toda alegria e paz, por sua confiança nele, para que vocês transbordem de esperança pelo poder do Espírito Santo.",
    version: "NVI",
    theme: "Esperança",
    period: "evening",
  },
  {
    id: 136,
    book: "Salmos",
    chapter: 31,
    verse: 5,
    text: "Nas tuas mãos entrego o meu espírito; resgata-me, Senhor, Deus da verdade.",
    version: "NVI",
    theme: "Fé",
    period: "evening",
  },
  {
    id: 137,
    book: "Salmos",
    chapter: 89,
    verse: "1-2",
    text: "Cantarei para sempre sobre o grande amor do Senhor; com a minha boca anunciarei a tua fidelidade por todas as gerações.",
    version: "NVI",
    theme: "Amor",
    period: "evening",
  },
  {
    id: 138,
    book: "Salmos",
    chapter: 145,
    verse: "18-19",
    text: "O Senhor está perto de todos os que o invocam, de todos os que o invocam com sinceridade. Ele realiza os desejos daqueles que o temem; ouve o seu clamor e os salva.",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 139,
    book: "Salmos",
    chapter: 138,
    verse: 3,
    text: "No dia em que clamei, tu me respondeste; deste-me força e coragem.",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 140,
    book: "Salmos",
    chapter: 139,
    verse: "17-18",
    text: "Como são preciosos para mim os teus pensamentos, ó Deus! Como é grande a soma deles! Se eu os contasse, seriam mais do que os grãos de areia; quando acordo, ainda estou contigo.",
    version: "NVI",
    theme: "Amor",
    period: "evening",
  },
  {
    id: 141,
    book: "Salmos",
    chapter: 147,
    verse: 3,
    text: "Ele sara os que têm o coração quebrantado e cuida das suas feridas.",
    version: "NVI",
    theme: "Amor",
    period: "evening",
  },
  {
    id: 142,
    book: "Salmos",
    chapter: 125,
    verse: "1-2",
    text: "Os que confiam no Senhor são como o monte Sião, que não se pode abalar, mas permanece para sempre. Como os montes cercam Jerusalém, assim o Senhor cerca o seu povo, desde agora e para sempre.",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
  {
    id: 143,
    book: "Salmos",
    chapter: 126,
    verse: 3,
    text: "Sim, coisas grandiosas fez o Senhor por nós, por isso estamos alegres.",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 144,
    book: "Colossenses",
    chapter: 3,
    verse: 15,
    text: "Que a paz de Cristo seja o juiz em seus corações, visto que vocês foram chamados para viver em paz, como membros de um só corpo. E sejam agradecidos.",
    version: "NVI",
    theme: "Paz",
    period: "evening",
  },
  {
    id: 145,
    book: "Salmos",
    chapter: 111,
    verse: 4,
    text: "Ele fez memoráveis as suas maravilhas; o Senhor é misericordioso e compassivo.",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 146,
    book: "Lamentações",
    chapter: 3,
    verse: 24,
    text: "Digo a mim mesmo: 'A minha porção é o Senhor; portanto, nele porei a minha esperança.'",
    version: "NVI",
    theme: "Esperança",
    period: "evening",
  },
  {
    id: 147,
    book: "Salmos",
    chapter: 71,
    verse: 5,
    text: "Pois tu és a minha esperança, ó Soberano Senhor, em ti está a minha confiança desde a minha juventude.",
    version: "NVI",
    theme: "Esperança",
    period: "evening",
  },
  {
    id: 148,
    book: "Salmos",
    chapter: 86,
    verse: 15,
    text: "Mas tu, Senhor, és Deus compassivo e misericordioso, muito paciente, rico em amor e fidelidade.",
    version: "NVI",
    theme: "Amor",
    period: "evening",
  },
  {
    id: 149,
    book: "1 João",
    chapter: 4,
    verse: 18,
    text: "No amor não há medo; ao contrário o perfeito amor expulsa o medo.",
    version: "NVI",
    theme: "Amor",
    period: "evening",
  },
  {
    id: 150,
    book: "Salmos",
    chapter: 92,
    verse: "1-2",
    text: "Como é bom render graças ao Senhor e cantar louvores ao teu nome, ó Altíssimo; anunciar de manhã o teu amor leal e de noite a tua fidelidade!",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 151,
    book: "Salmos",
    chapter: 103,
    verse: 13,
    text: "Como um pai tem compaixão de seus filhos, assim o Senhor tem compaixão dos que o temem.",
    version: "NVI",
    theme: "Amor",
    period: "evening",
  },
  {
    id: 152,
    book: "Salmos",
    chapter: 104,
    verse: 34,
    text: "Seja-lhe agradável a minha meditação; eu me alegrarei no Senhor.",
    version: "NVI",
    theme: "Gratidão",
    period: "evening",
  },
  {
    id: 153,
    book: "Salmos",
    chapter: 130,
    verse: 5,
    text: "Espero no Senhor com todo o meu ser, e na sua palavra ponho a minha esperança.",
    version: "NVI",
    theme: "Esperança",
    period: "evening",
  },
  {
    id: 154,
    book: "Salmos",
    chapter: 143,
    verse: 10,
    text: "Ensina-me a fazer a tua vontade, pois tu és o meu Deus; que o teu bom Espírito me guie por terra plana.",
    version: "NVI",
    theme: "Sabedoria",
    period: "evening",
  },
  {
    id: 155,
    book: "Números",
    chapter: 6,
    verse: "24-26",
    text: "O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti e tenha misericórdia de ti; o Senhor sobre ti levante o seu rosto e te dê a paz.",
    version: "NVI",
    theme: "Proteção",
    period: "evening",
  },
];
