export interface BibleVerse {
  id: number;
  book: string;
  chapter: number;
  verse: number | string;
  text: string;
  version: "NVI" | "ACF";
  theme: "Paz" | "Fé" | "Força" | "Sabedoria" | "Esperança" | "Amor" | "Gratidão" | "Proteção";
}

export const CURATED_VERSES: BibleVerse[] = [
  {
    id: 1,
    book: "Salmos",
    chapter: 23,
    verse: "1-2",
    text: "O Senhor é o meu pastor; de nada terei falta. Em verdes pastagens me faz repousar e me conduz a águas tranquilas.",
    version: "NVI",
    theme: "Paz",
  },
  {
    id: 2,
    book: "Filipenses",
    chapter: 4,
    verse: "6-7",
    text: "Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus. E a paz de Deus, que excede todo o entendimento, guardará os seus corações e as suas mentes em Cristo Jesus.",
    version: "NVI",
    theme: "Paz",
  },
  {
    id: 3,
    book: "Isaías",
    chapter: 41,
    verse: 10,
    text: "Por isso não tema, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa.",
    version: "NVI",
    theme: "Força",
  },
  {
    id: 4,
    book: "Provérbios",
    chapter: 3,
    verse: "5-6",
    text: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.",
    version: "NVI",
    theme: "Sabedoria",
  },
  {
    id: 5,
    book: "Jeremias",
    chapter: 29,
    verse: 11,
    text: "Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor, planos de fazê-los prosperar e não de causar dano, planos de dar a vocês esperança e um futuro.",
    version: "NVI",
    theme: "Esperança",
  },
  {
    id: 6,
    book: "Josué",
    chapter: 1,
    verse: 9,
    text: "Não fui eu que ordenei a você? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.",
    version: "NVI",
    theme: "Força",
  },
  {
    id: 7,
    book: "Salmos",
    chapter: 46,
    verse: 1,
    text: "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade.",
    version: "NVI",
    theme: "Proteção",
  },
  {
    id: 8,
    book: "Romanos",
    chapter: 8,
    verse: 28,
    text: "Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito.",
    version: "NVI",
    theme: "Fé",
  },
  {
    id: 9,
    book: "Salmos",
    chapter: 91,
    verse: "1-2",
    text: "Aquele que habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso pode dizer ao Senhor: 'Tu és o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.'",
    version: "NVI",
    theme: "Proteção",
  },
  {
    id: 10,
    book: "Mateus",
    chapter: 6,
    verse: 33,
    text: "Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas.",
    version: "NVI",
    theme: "Fé",
  },
  {
    id: 11,
    book: "Salmos",
    chapter: 121,
    verse: "1-2",
    text: "Levanto os meus olhos para os montes e pergunto: de onde me vem o socorro? O meu socorro vem do Senhor, que fez os céus e a terra.",
    version: "NVI",
    theme: "Proteção",
  },
  {
    id: 12,
    book: "Lamentações",
    chapter: 3,
    verse: "22-23",
    text: "Graças ao grande amor do Senhor é que não somos consumidos, pois as suas misericórdias são inesgotáveis. Renovam-se a cada manhã; grande é a sua fidelidade!",
    version: "NVI",
    theme: "Esperança",
  },
  {
    id: 13,
    book: "1 Tessalonicenses",
    chapter: 5,
    verse: "16-18",
    text: "Alegrem-se sempre. Orem continuamente. Dêem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.",
    version: "NVI",
    theme: "Gratidão",
  },
  {
    id: 14,
    book: "Provérbios",
    chapter: 16,
    verse: 3,
    text: "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.",
    version: "NVI",
    theme: "Sabedoria",
  },
  {
    id: 15,
    book: "Salmos",
    chapter: 37,
    verse: 5,
    text: "Entregue o seu caminho ao Senhor; confie nele, e ele agirá.",
    version: "NVI",
    theme: "Fé",
  },
  {
    id: 16,
    book: "Isaías",
    chapter: 40,
    verse: 31,
    text: "Mas aqueles que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam.",
    version: "NVI",
    theme: "Força",
  },
  {
    id: 17,
    book: "Hebreus",
    chapter: 11,
    verse: 1,
    text: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.",
    version: "NVI",
    theme: "Fé",
  },
  {
    id: 18,
    book: "João",
    chapter: 14,
    verse: 27,
    text: "Deixo-lhes a paz; a minha paz lhes dou. Não lha dou como o mundo a dá. Não se perturbe o seu coração, nem tenham medo.",
    version: "NVI",
    theme: "Paz",
  },
  {
    id: 19,
    book: "Romanos",
    chapter: 12,
    verse: 12,
    text: "Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.",
    version: "NVI",
    theme: "Esperança",
  },
  {
    id: 20,
    book: "Salmos",
    chapter: 118,
    verse: 24,
    text: "Este é o dia que fez o Senhor; regozijemo-nos e alegremo-nos nele.",
    version: "NVI",
    theme: "Gratidão",
  },
  {
    id: 21,
    book: "Efésios",
    chapter: 3,
    verse: 20,
    text: "Àquele que é capaz de fazer infinitamente mais do que tudo o que pedimos ou pensamos, de acordo com o seu poder que atua em nós.",
    version: "NVI",
    theme: "Fé",
  },
  {
    id: 22,
    book: "Salmos",
    chapter: 119,
    verse: 105,
    text: "Lâmpada para os meus pés é a tua palavra e luz, para o meu caminho.",
    version: "NVI",
    theme: "Sabedoria",
  },
  {
    id: 23,
    book: "Filipenses",
    chapter: 4,
    verse: 13,
    text: "Tudo posso naquele que me fortalece.",
    version: "NVI",
    theme: "Força",
  },
  {
    id: 24,
    book: "1 Coríntios",
    chapter: 13,
    verse: "4-7",
    text: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha. Não maltrata, não procura seus interesses, não se ira facilmente, não guarda rancor. Tudo sofre, tudo crê, tudo espera, tudo suporta.",
    version: "NVI",
    theme: "Amor",
  },
  {
    id: 25,
    book: "Salmos",
    chapter: 34,
    verse: 8,
    text: "Provem e vejam como o Senhor é bom. Como é feliz o homem que nele se refugia!",
    version: "NVI",
    theme: "Gratidão",
  },
  {
    id: 26,
    book: "Tiago",
    chapter: 1,
    verse: 5,
    text: "Se algum de vocês tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida.",
    version: "NVI",
    theme: "Sabedoria",
  },
  {
    id: 27,
    book: "Salmos",
    chapter: 103,
    verse: "1-2",
    text: "Bendigam ao Senhor, ó minha alma! Bendiga ao Senhor todo o meu ser! Não se esqueçam de nenhuma das suas bênçãos!",
    version: "NVI",
    theme: "Gratidão",
  },
  {
    id: 28,
    book: "Gálatas",
    chapter: 5,
    verse: "22-23",
    text: "Mas o fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidão e domínio próprio.",
    version: "NVI",
    theme: "Paz",
  },
  {
    id: 29,
    book: "Mateus",
    chapter: 11,
    verse: 28,
    text: "Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso.",
    version: "NVI",
    theme: "Paz",
  },
  {
    id: 30,
    book: "Romanos",
    chapter: 8,
    verse: 31,
    text: "Que diremos, pois, diante dessas coisas? Se Deus é por nós, quem será contra nós?",
    version: "NVI",
    theme: "Força",
  },
  {
    id: 31,
    book: "Salmos",
    chapter: 27,
    verse: 1,
    text: "O Senhor é a minha luz e a minha salvação; de quem terei temor? O Senhor é a fortaleza da minha vida; a quem temerei?",
    version: "NVI",
    theme: "Proteção",
  },
];
